---
title: "Comparison with dplyr"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design Motivation}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



There are an increasing number of data frame packages in R, including
[data.table][data-table] and [dplyr][dplyr]. All provide similar
functionality, but they do so with different user interfaces. To illustrate
some of the differences, this vignette translates the
[dplyr introduction][dplyr-intro] to *frame*.  


```r
library(frame)
```

## Data: nycflights13

The [nycflights13][nycflights13] package collects flight information from 2013 for trips
originating or ending in New York City. The package provides the data in the
form of `tibble` objects, but we can easily convert them to datasets using
`as_data`.


```r
library(nycflights13)
flights <- as_dataset(flights)
print(flights)
#>    year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time
#> 1  2013     1   1      517            515         2      830            819
#> 2  2013     1   1      533            529         4      850            830
#> 3  2013     1   1      542            540         2      923            850
#> 4  2013     1   1      544            545        -1     1004           1022
#> 5  2013     1   1      554            600        -6      812            837
#> 6  2013     1   1      554            558        -4      740            728
#> 7  2013     1   1      555            600        -5      913            854
#> 8  2013     1   1      557            600        -3      709            723
#> 9  2013     1   1      557            600        -3      838            846
#> 10 2013     1   1      558            600        -2      753            745
#> 11 2013     1   1      558            600        -2      849            851
#> 12 2013     1   1      558            600        -2      853            856
#> 13 2013     1   1      558            600        -2      924            917
#> 14 2013     1   1      558            600        -2      923            937
#> 15 2013     1   1      559            600        -1      941            910
#> 16 2013     1   1      559            559         0      702            706
#> 17 2013     1   1      559            600        -1      854            902
#> 18 2013     1   1      600            600         0      851            858
#> 19 2013     1   1      600            600         0      837            825
#> 20 2013     1   1      601            600         1      844            850
#> ⋮
#>    arr_delay carrier flight tailnum origin dest air_time distance hour minute
#> 1         11 UA        1545 N14228  EWR    IAH       227     1400    5     15
#> 2         20 UA        1714 N24211  LGA    IAH       227     1416    5     29
#> 3         33 AA        1141 N619AA  JFK    MIA       160     1089    5     40
#> 4        -18 B6         725 N804JB  JFK    BQN       183     1576    5     45
#> 5        -25 DL         461 N668DN  LGA    ATL       116      762    6      0
#> 6         12 UA        1696 N39463  EWR    ORD       150      719    5     58
#> 7         19 B6         507 N516JB  EWR    FLL       158     1065    6      0
#> 8        -14 EV        5708 N829AS  LGA    IAD        53      229    6      0
#> 9         -8 B6          79 N593JB  JFK    MCO       140      944    6      0
#> 10         8 AA         301 N3ALAA  LGA    ORD       138      733    6      0
#> 11        -2 B6          49 N793JB  JFK    PBI       149     1028    6      0
#> 12        -3 B6          71 N657JB  JFK    TPA       158     1005    6      0
#> 13         7 UA         194 N29129  JFK    LAX       345     2475    6      0
#> 14       -14 UA        1124 N53441  EWR    SFO       361     2565    6      0
#> 15        31 AA         707 N3DUAA  LGA    DFW       257     1389    6      0
#> 16        -4 B6        1806 N708JB  JFK    BOS        44      187    5     59
#> 17        -8 UA        1187 N76515  EWR    LAS       337     2227    6      0
#> 18        -7 B6         371 N595JB  LGA    FLL       152     1076    6      0
#> 19        12 MQ        4650 N542MQ  LGA    ATL       134      762    6      0
#> 20        -6 B6         343 N644JB  EWR    PBI       147     1023    6      0
#> ⋮
#>    time_hour          
#> 1  2013-01-01 05:00:00
#> 2  2013-01-01 05:00:00
#> 3  2013-01-01 05:00:00
#> 4  2013-01-01 05:00:00
#> 5  2013-01-01 06:00:00
#> 6  2013-01-01 05:00:00
#> 7  2013-01-01 06:00:00
#> 8  2013-01-01 06:00:00
#> 9  2013-01-01 06:00:00
#> 10 2013-01-01 06:00:00
#> 11 2013-01-01 06:00:00
#> 12 2013-01-01 06:00:00
#> 13 2013-01-01 06:00:00
#> 14 2013-01-01 06:00:00
#> 15 2013-01-01 06:00:00
#> 16 2013-01-01 05:00:00
#> 17 2013-01-01 06:00:00
#> 18 2013-01-01 06:00:00
#> 19 2013-01-01 06:00:00
#> 20 2013-01-01 06:00:00
#> ⋮                                                         (336776 rows total)
```

There are more rows in this dataset than will fit on the screen.  By default,
then `print` function will only display 20 rows, and only wrap columns at most
twice.  Change the default to another value using the following command:


```r
options(frame.rows = 5) # truncate output after 5 rows
options(frame.wrap = 0) # truncate output after wrapping columns once
```

*frame* uses the default value of 20 to display as much data as possible
without overflowing the space on a standard console. For the rest of this
vignette, however, we will be demonstrating programming, not data analysis, so
we will truncate the output to 4 rows and no wraps.



```r
print(flights)
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   1      517            515         2      830            819 …
#> 2 2013     1   1      533            529         4      850            830 …
#> 3 2013     1   1      542            540         2      923            850 …
#> 4 2013     1   1      544            545        -1     1004           1022 …
#> 5 2013     1   1      554            600        -6      812            837 …
#> ⋮                                            (336776 rows, 19 columns total)
```

You can get information about the column types using the `schema` function,
which itself returns a `dataset`:


```r
schema(flights)
#> id │ name           class  
#>  1 │ year           integer
#>  2 │ month          integer
#>  3 │ day            integer
#>  4 │ dep_time       integer
#>  5 │ sched_dep_time integer
#> ⋮           (19 rows total)
```

This is one example where we would like to see more rows than displayed by our
newly-specified default (5). Display all rows of the result by specifying a
negative value for the truncation limit:


```r
print(schema(flights), -1)
#> id │ name           class    
#>  1 │ year           integer  
#>  2 │ month          integer  
#>  3 │ day            integer  
#>  4 │ dep_time       integer  
#>  5 │ sched_dep_time integer  
#>  6 │ dep_delay      numeric  
#>  7 │ arr_time       integer  
#>  8 │ sched_arr_time integer  
#>  9 │ arr_delay      numeric  
#> 10 │ carrier        character
#> 11 │ flight         integer  
#> 12 │ tailnum        character
#> 13 │ origin         character
#> 14 │ dest           character
#> 15 │ air_time       numeric  
#> 16 │ distance       numeric  
#> 17 │ hour           numeric  
#> 18 │ minute         numeric  
#> 19 │ time_hour      POSIXct
```


## Single table actions

Dplyr provides a set of "verbs" for working with data sets. We do not provide
analogues for most of them, but often it is possible to use functions built in
to R to achieve their same results.

### Filter rows with `subset()`

Use the `subset` command (part of base R) to select certain rows:


```r
subset(flights, month == 1 & day == 1)
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   1      517            515         2      830            819 …
#> 2 2013     1   1      533            529         4      850            830 …
#> 3 2013     1   1      542            540         2      923            850 …
#> 4 2013     1   1      544            545        -1     1004           1022 …
#> 5 2013     1   1      554            600        -6      812            837 …
#> ⋮                                               (842 rows, 19 columns total)
```

This is analogous to `dplyr::filter()`.


### Arrange rows with `reorder()`

Use `reorder()` to arrange rows, using the first argument and then breaking
ties according to subsequent arguments.



```r
reorder(flights, year, month, day)
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   1      517            515         2      830            819 …
#> 2 2013     1   1      533            529         4      850            830 …
#> 3 2013     1   1      542            540         2      923            850 …
#> 4 2013     1   1      544            545        -1     1004           1022 …
#> 5 2013     1   1      554            600        -6      812            837 …
#> ⋮                                            (336776 rows, 19 columns total)
```

This is analogous to `dplyr::arrange()`.

Use a named argument (`"desc")` to order in descending order.


```r
reorder(flights, desc = arr_delay)
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   9      641            900      1301     1242           1530 …
#> 2 2013     6  15     1432           1935      1137     1607           2120 …
#> 3 2013     1  10     1121           1635      1126     1239           1810 …
#> 4 2013     9  20     1139           1845      1014     1457           2210 …
#> 5 2013     7  22      845           1600      1005     1044           1815 …
#> ⋮                                            (336776 rows, 19 columns total)
```

You can specify multiple descending columns if you'd like:


```r
# descending arr_delay, distance; ascending day
reorder(flights,
        desc = arr_delay,
        desc = distance,
        day)
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   9      641            900      1301     1242           1530 …
#> 2 2013     6  15     1432           1935      1137     1607           2120 …
#> 3 2013     1  10     1121           1635      1126     1239           1810 …
#> 4 2013     9  20     1139           1845      1014     1457           2210 …
#> 5 2013     7  22      845           1600      1005     1044           1815 …
#> ⋮                                            (336776 rows, 19 columns total)
```


### Select columns with `[` or `subset()`

Use the subscript operator `[` or the `subset()` function to select columns:


```r
flights[c("year", "month", "day")]
#>   year month day
#> 1 2013     1   1
#> 2 2013     1   1
#> 3 2013     1   1
#> 4 2013     1   1
#> 5 2013     1   1
#> ⋮ (336776 rows total)
subset(flights, select = c(year, month, day))
#>   year month day
#> 1 2013     1   1
#> 2 2013     1   1
#> 3 2013     1   1
#> 4 2013     1   1
#> 5 2013     1   1
#> ⋮ (336776 rows total)
```

You can specify columns using a numerical index, or a set of indices; use
negative indices to exclude columns.


```r
flights[1:3]
#>   year month day
#> 1 2013     1   1
#> 2 2013     1   1
#> 3 2013     1   1
#> 4 2013     1   1
#> 5 2013     1   1
#> ⋮ (336776 rows total)
flights[-(1:3)] # exclude 1:3
#>   dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay carrier …
#> 1      517            515         2      830            819        11 UA      …
#> 2      533            529         4      850            830        20 UA      …
#> 3      542            540         2      923            850        33 AA      …
#> 4      544            545        -1     1004           1022       -18 B6      …
#> 5      554            600        -6      812            837       -25 DL      …
#> ⋮                                               (336776 rows, 16 columns total)
```

If you don't know the index of a column, you can get it like with the base R
`match` function:


```r
match("day", names(flights))
#> [1] 3
```

With `subset()`, you can specify ranges in terms of the names themselves, 


```r
subset(fligths, select = year:day)
#> Error in subset(fligths, select = year:day): object 'fligths' not found
subset(flights, select = -(year:day)) # exclude year:day
#>   dep_time sched_dep_time dep_delay arr_time sched_arr_time arr_delay carrier …
#> 1      517            515         2      830            819        11 UA      …
#> 2      533            529         4      850            830        20 UA      …
#> 3      542            540         2      923            850        33 AA      …
#> 4      544            545        -1     1004           1022       -18 B6      …
#> 5      554            600        -6      812            837       -25 DL      …
#> ⋮                                               (336776 rows, 16 columns total)
```

These functions are analogous to `dplyr::select()`.


### Add new columns with transform()

Use the `transform` function from base R to add new columns:


```r
transform(flights,
    gain = arr_delay - dep_delay,
    speed = distance / air_time * 60
)
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   1      517            515         2      830            819 …
#> 2 2013     1   1      533            529         4      850            830 …
#> 3 2013     1   1      542            540         2      923            850 …
#> 4 2013     1   1      544            545        -1     1004           1022 …
#> 5 2013     1   1      554            600        -6      812            837 …
#> ⋮                                            (336776 rows, 21 columns total)
```

This is similar to `dplyr::mutate`, but it does not evaluate columns
sequentially. If you need sequential modifications, use `within()`:


```r
within(flights, {
    gain <- arr_delay - dep_delay
    gain_per_hour <- gain / (air_time / 60)
})
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1   1      517            515         2      830            819 …
#> 2 2013     1   1      533            529         4      850            830 …
#> 3 2013     1   1      542            540         2      923            850 …
#> 4 2013     1   1      544            545        -1     1004           1022 …
#> 5 2013     1   1      554            600        -6      812            837 …
#> ⋮                                            (336776 rows, 21 columns total)
```

If you only want to keep the new variables, use `with()` and return a
dataset.


```r
with(flights, {
    gain <- arr_delay - dep_delay
    gain_per_hour <- gain / (air_time / 60)
    dataset(gain, gain_per_hour)
})
#>   gain gain_per_hour
#> 1    9      2.378855
#> 2   16      4.229075
#> 3   31     11.625000
#> 4  -17     -5.573770
#> 5  -19     -9.827586
#> ⋮ (336776 rows total)
```

### Summarize values with `with()`

The `with()` command can also be used to summarize data:


```r
with(flights, {
    mean(dep_delay, na.rm = TRUE)
})
#> [1] 12.63907
```

This is analogous to `dplyr::summarise()`.


### Randomly sample rows with `sample()`

There are no direct analogues to *dplyr* `dplyr::sample_n()` and
`dplyr::sample_frac()`, but you can get a random sample of the rows, use the
`sample()` function. Use `sample()` to choose a random set of row indices, and
then select these with the subset operator:


```r
# sample 10 rows
flights[sample(nrow(flights), 10), ]
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     8  24      547            545         2      816            815 …
#> 2 2013    12   7     1447           1445         2     1842           1812 …
#> 3 2013     2  17      809            810        -1     1024           1042 …
#> 4 2013     4  30     1354           1359        -5     1447           1519 …
#> 5 2013     8  28      905            910        -5     1203           1215 …
#> ⋮                                                (10 rows, 19 columns total)
```

Use `replace = TRUE` to sample with replacement, as for a bootstrap sample.


```r
# get a bootstrap sample
flights[sample(nrow(flights), replace = TRUE), ]
#>   year month day dep_time sched_dep_time dep_delay arr_time sched_arr_time …
#> 1 2013     1  24     1948           1920        28     2102           2100 …
#> 2 2013    11  15     1342           1345        -3     1525           1520 …
#> 3 2013    11   5      554            600        -6      705            719 …
#> 4 2013     6  10       NA           2105        NA       NA           2305 …
#> 5 2013     2  21     1356           1238        78     1615           1435 …
#> ⋮                                            (336776 rows, 19 columns total)
```


### Grouped operations

Use the `grouped()` command to perform an operation on a set of groups
defined by the unique levels of one or more variables:


```r
delay <- grouped(flights, "tailnum", function(x) {
    list(count = nrow(x),
         dist = mean(x$distance, na.rm = TRUE),
         delay = mean(x$arr_delay, na.rm = TRUE))
})

(delay <- subset(delay, count > 20 & dist < 2000))
#> tailnum │ count     dist     delay
#> N0EGMQ  │   371 676.1887  9.982955
#> N10156  │   153 757.9477 12.717241
#> N102UW  │    48 535.8750  2.937500
#> N103US  │    46 535.1957 -6.934783
#> N104UW  │    47 535.2553  1.804348
#> ⋮                (2962 rows total)
```

The `grouped()` command acts as a combination of `dplyr::group_by()` and
`dplyr::summarise()`. To group the rows but not perform any computation,
leave the operation specified:


```r
grouped(flights, "tailnum")
#> tailnum │ [,1]           
#> D942DN  │ dataset[4×18]  
#> N0EGMQ  │ dataset[371×18]
#> N10156  │ dataset[153×18]
#> N102UW  │ dataset[48×18] 
#> N103US  │ dataset[46×18] 
#> ⋮       (4044 rows total)
```

Here the result is a `dataset`  with keys taken from the `tailnum` variable.
The dataset has a single column: a list of the groups.

Here's how to find the number of planes and the number of flights that go to
each possible destination:


```r
grouped(flights, "dest", function(x) {
    list(planes = length(unique(x$tailnum)),
         flights = nrow(x))
})
#> dest │ planes flights
#> ABQ  │    108     254
#> ACK  │     58     265
#> ALB  │    172     439
#> ANC  │      6       8
#> ATL  │   1180   17215
#> ⋮    (105 rows total)
```

The grouping variables specified as names must be data variables, not keys. If
you would like to group by a key, do the following instead:


```r
# helper functions
count <- function(x) list(flights = nrow(x))
total <- function(x) list(flights = sum(x$flights))

# count daily flights...
(per_day <- grouped(flights, c("year", "month", "day"), count))
#> year month day │ flights
#> 2013     1   1 │     842
#> 2013     1   2 │     943
#> 2013     1   3 │     914
#> 2013     1   4 │     915
#> 2013     1   5 │     720
#> ⋮       (365 rows total)

# ...then aggregate by month
(per_month <- grouped(per_day, keys(per_day)[c("year", "month")], total))
#> year month │ flights
#> 2013     1 │   27004
#> 2013     2 │   24951
#> 2013     3 │   28834
#> 2013     4 │   28330
#> 2013     5 │   28796
#> ⋮    (12 rows total)

# ...then aggregate by year
(per_year <- grouped(per_month, keys(per_month)["year"], total))
#> year │ flights
#> 2013 │  336776
```


[data-table]: http://r-datatable.com/ "data.table"
[dplyr]: http://dplyr.tidyverse.org/ "dplyr"
[dplyr-intro]: https://cran.r-project.org/package=dplyr/vignettes/dplyr.html "An introduction to dplyr"
[nycflights13]: https://cran.r-project.org/package=nycflights13 "nycflights13"
